### PR TITLE
Document new code example of pushing TTT results to Git. Some text

### PR DESCRIPTION
**Pull request by ralphnuessecpwr**
I added a new example to the Examples repository, I created for one of our customers (https://github.com/cpwr-devops/DevOps-Examples/blob/RXN_Push_TTT_Results_To_Git/src/Jenkinsfile/Push_TTT_results_to_Git.jenkinsfile).
I added the documentation for this code, repaired some broken links, and added some description to using the Compuware plugins.

### CODE REVIEW

**Comment by ralphnuessecpwr** [comment]
The structure is far more concise - I like it, and thank you for taking care of broken links. Must have been a hell of a job. 
I am a bit confused about the items in the navbar and the sidebar. Different headings seem to take you to the same place, and I personally was confused by not being able to find the "Getting Started" again - at least not under this heading: In the "Pipelines" navbar item it is "Basic Pipelines Example", while the links takes you to the "Getting Started" page. I would have expected that "Basic Pipelines Example" takes me to Mainframe-CI-Example-pipeline.html, and that there is an item "Getting started".
Still, I think, I understand the idea behind the navbar content in contrast to the sidebar. 
On other thing: Considering that we will publish some more "special purpose" pipelines (like the last one "pushing to GitHub") would it make sense to add a "group" (sub folder) for them. At least in the future, once we have more examples? Otherwise, the sidebar might start getting cluttered?

**Comment by ralphnuessecpwr** [comment]
I modified the config.js slightly to show what I mean. If you don't like it, config.js.old_rxn contains the original version. 
Also, I added introduction paragraphs to some of the pages and added h1 headings at the top of pages where they were missing.
Looking at some pages, I am wondering if we need to define a "style" guide, so that we use emphasis (*) and code markers (`) consistently. E.g. sometimes I use * for paths and file names, sometimes I use `. Similarly for menu items like "Manage Jenkins" -> "Manage Plugins". 
What would be your recommendation? My feeling tells me to use ` only for code like class names or method names, and * in all other cases.

**Comment by steve-kansa** [comment]
I like the changes you made.  I've done a couple more tweaks and if you are good with the changes, I can merge this into the master.

**Comment by ralphnuessecpwr** [comment]
I'm good with it. Might review spelling errors over time, but no structural changes any time soon. So, yes, go ahead and merge.

**Pull request merged**
